version: '2'

services:
  app:
    image: 'inventory-service:latest'
    build:
      context: .
    container_name: cihan-app
    depends_on:
      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:jdbc:mysql://localhost:3306/inventory-service?useLegacyDatetimeCode=false&serverTimezone=Turkey
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
#      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_DATASOURCE_INITIALIZATION_MODE=always

  db:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: inventory-service
      ports:
        - '3306:3306'
